/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison interface for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

#ifndef YY_ASLCOMPILER_GENERATE_MSVC2017_ASLCOMPILER_Y_H_INCLUDED
# define YY_ASLCOMPILER_GENERATE_MSVC2017_ASLCOMPILER_Y_H_INCLUDED
/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 0
#endif
#if YYDEBUG
extern int AslCompilerdebug;
#endif

/* Token kinds.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    YYEMPTY = -2,
    YYEOF = 0,                     /* "end of file"  */
    YYerror = 256,                 /* error  */
    YYUNDEF = 257,                 /* "invalid token"  */
    PARSEOP_ACCESSAS = 258,        /* PARSEOP_ACCESSAS  */
    PARSEOP_ACCESSATTRIB_BLOCK = 259, /* PARSEOP_ACCESSATTRIB_BLOCK  */
    PARSEOP_ACCESSATTRIB_BLOCK_CALL = 260, /* PARSEOP_ACCESSATTRIB_BLOCK_CALL  */
    PARSEOP_ACCESSATTRIB_BYTE = 261, /* PARSEOP_ACCESSATTRIB_BYTE  */
    PARSEOP_ACCESSATTRIB_BYTES = 262, /* PARSEOP_ACCESSATTRIB_BYTES  */
    PARSEOP_ACCESSATTRIB_QUICK = 263, /* PARSEOP_ACCESSATTRIB_QUICK  */
    PARSEOP_ACCESSATTRIB_RAW_BYTES = 264, /* PARSEOP_ACCESSATTRIB_RAW_BYTES  */
    PARSEOP_ACCESSATTRIB_RAW_PROCESS = 265, /* PARSEOP_ACCESSATTRIB_RAW_PROCESS  */
    PARSEOP_ACCESSATTRIB_SND_RCV = 266, /* PARSEOP_ACCESSATTRIB_SND_RCV  */
    PARSEOP_ACCESSATTRIB_WORD = 267, /* PARSEOP_ACCESSATTRIB_WORD  */
    PARSEOP_ACCESSATTRIB_WORD_CALL = 268, /* PARSEOP_ACCESSATTRIB_WORD_CALL  */
    PARSEOP_ACCESSTYPE_ANY = 269,  /* PARSEOP_ACCESSTYPE_ANY  */
    PARSEOP_ACCESSTYPE_BUF = 270,  /* PARSEOP_ACCESSTYPE_BUF  */
    PARSEOP_ACCESSTYPE_BYTE = 271, /* PARSEOP_ACCESSTYPE_BYTE  */
    PARSEOP_ACCESSTYPE_DWORD = 272, /* PARSEOP_ACCESSTYPE_DWORD  */
    PARSEOP_ACCESSTYPE_QWORD = 273, /* PARSEOP_ACCESSTYPE_QWORD  */
    PARSEOP_ACCESSTYPE_WORD = 274, /* PARSEOP_ACCESSTYPE_WORD  */
    PARSEOP_ACQUIRE = 275,         /* PARSEOP_ACQUIRE  */
    PARSEOP_ADD = 276,             /* PARSEOP_ADD  */
    PARSEOP_ADDRESSINGMODE_7BIT = 277, /* PARSEOP_ADDRESSINGMODE_7BIT  */
    PARSEOP_ADDRESSINGMODE_10BIT = 278, /* PARSEOP_ADDRESSINGMODE_10BIT  */
    PARSEOP_ADDRESSTYPE_ACPI = 279, /* PARSEOP_ADDRESSTYPE_ACPI  */
    PARSEOP_ADDRESSTYPE_MEMORY = 280, /* PARSEOP_ADDRESSTYPE_MEMORY  */
    PARSEOP_ADDRESSTYPE_NVS = 281, /* PARSEOP_ADDRESSTYPE_NVS  */
    PARSEOP_ADDRESSTYPE_RESERVED = 282, /* PARSEOP_ADDRESSTYPE_RESERVED  */
    PARSEOP_ALIAS = 283,           /* PARSEOP_ALIAS  */
    PARSEOP_AND = 284,             /* PARSEOP_AND  */
    PARSEOP_ARG0 = 285,            /* PARSEOP_ARG0  */
    PARSEOP_ARG1 = 286,            /* PARSEOP_ARG1  */
    PARSEOP_ARG2 = 287,            /* PARSEOP_ARG2  */
    PARSEOP_ARG3 = 288,            /* PARSEOP_ARG3  */
    PARSEOP_ARG4 = 289,            /* PARSEOP_ARG4  */
    PARSEOP_ARG5 = 290,            /* PARSEOP_ARG5  */
    PARSEOP_ARG6 = 291,            /* PARSEOP_ARG6  */
    PARSEOP_BANKFIELD = 292,       /* PARSEOP_BANKFIELD  */
    PARSEOP_BITSPERBYTE_EIGHT = 293, /* PARSEOP_BITSPERBYTE_EIGHT  */
    PARSEOP_BITSPERBYTE_FIVE = 294, /* PARSEOP_BITSPERBYTE_FIVE  */
    PARSEOP_BITSPERBYTE_NINE = 295, /* PARSEOP_BITSPERBYTE_NINE  */
    PARSEOP_BITSPERBYTE_SEVEN = 296, /* PARSEOP_BITSPERBYTE_SEVEN  */
    PARSEOP_BITSPERBYTE_SIX = 297, /* PARSEOP_BITSPERBYTE_SIX  */
    PARSEOP_BREAK = 298,           /* PARSEOP_BREAK  */
    PARSEOP_BREAKPOINT = 299,      /* PARSEOP_BREAKPOINT  */
    PARSEOP_BUFFER = 300,          /* PARSEOP_BUFFER  */
    PARSEOP_BUSMASTERTYPE_MASTER = 301, /* PARSEOP_BUSMASTERTYPE_MASTER  */
    PARSEOP_BUSMASTERTYPE_NOTMASTER = 302, /* PARSEOP_BUSMASTERTYPE_NOTMASTER  */
    PARSEOP_BYTECONST = 303,       /* PARSEOP_BYTECONST  */
    PARSEOP_CASE = 304,            /* PARSEOP_CASE  */
    PARSEOP_CLOCKPHASE_FIRST = 305, /* PARSEOP_CLOCKPHASE_FIRST  */
    PARSEOP_CLOCKPHASE_SECOND = 306, /* PARSEOP_CLOCKPHASE_SECOND  */
    PARSEOP_CLOCKPOLARITY_HIGH = 307, /* PARSEOP_CLOCKPOLARITY_HIGH  */
    PARSEOP_CLOCKPOLARITY_LOW = 308, /* PARSEOP_CLOCKPOLARITY_LOW  */
    PARSEOP_CONCATENATE = 309,     /* PARSEOP_CONCATENATE  */
    PARSEOP_CONCATENATERESTEMPLATE = 310, /* PARSEOP_CONCATENATERESTEMPLATE  */
    PARSEOP_CONDREFOF = 311,       /* PARSEOP_CONDREFOF  */
    PARSEOP_CONNECTION = 312,      /* PARSEOP_CONNECTION  */
    PARSEOP_CONTINUE = 313,        /* PARSEOP_CONTINUE  */
    PARSEOP_COPYOBJECT = 314,      /* PARSEOP_COPYOBJECT  */
    PARSEOP_CREATEBITFIELD = 315,  /* PARSEOP_CREATEBITFIELD  */
    PARSEOP_CREATEBYTEFIELD = 316, /* PARSEOP_CREATEBYTEFIELD  */
    PARSEOP_CREATEDWORDFIELD = 317, /* PARSEOP_CREATEDWORDFIELD  */
    PARSEOP_CREATEFIELD = 318,     /* PARSEOP_CREATEFIELD  */
    PARSEOP_CREATEQWORDFIELD = 319, /* PARSEOP_CREATEQWORDFIELD  */
    PARSEOP_CREATEWORDFIELD = 320, /* PARSEOP_CREATEWORDFIELD  */
    PARSEOP_DATABUFFER = 321,      /* PARSEOP_DATABUFFER  */
    PARSEOP_DATATABLEREGION = 322, /* PARSEOP_DATATABLEREGION  */
    PARSEOP_DEBUG = 323,           /* PARSEOP_DEBUG  */
    PARSEOP_DECODETYPE_POS = 324,  /* PARSEOP_DECODETYPE_POS  */
    PARSEOP_DECODETYPE_SUB = 325,  /* PARSEOP_DECODETYPE_SUB  */
    PARSEOP_DECREMENT = 326,       /* PARSEOP_DECREMENT  */
    PARSEOP_DEFAULT = 327,         /* PARSEOP_DEFAULT  */
    PARSEOP_DEFAULT_ARG = 328,     /* PARSEOP_DEFAULT_ARG  */
    PARSEOP_DEFINITION_BLOCK = 329, /* PARSEOP_DEFINITION_BLOCK  */
    PARSEOP_DEREFOF = 330,         /* PARSEOP_DEREFOF  */
    PARSEOP_DEVICE = 331,          /* PARSEOP_DEVICE  */
    PARSEOP_DEVICEPOLARITY_HIGH = 332, /* PARSEOP_DEVICEPOLARITY_HIGH  */
    PARSEOP_DEVICEPOLARITY_LOW = 333, /* PARSEOP_DEVICEPOLARITY_LOW  */
    PARSEOP_DIVIDE = 334,          /* PARSEOP_DIVIDE  */
    PARSEOP_DMA = 335,             /* PARSEOP_DMA  */
    PARSEOP_DMATYPE_A = 336,       /* PARSEOP_DMATYPE_A  */
    PARSEOP_DMATYPE_COMPATIBILITY = 337, /* PARSEOP_DMATYPE_COMPATIBILITY  */
    PARSEOP_DMATYPE_B = 338,       /* PARSEOP_DMATYPE_B  */
    PARSEOP_DMATYPE_F = 339,       /* PARSEOP_DMATYPE_F  */
    PARSEOP_DWORDCONST = 340,      /* PARSEOP_DWORDCONST  */
    PARSEOP_DWORDIO = 341,         /* PARSEOP_DWORDIO  */
    PARSEOP_DWORDMEMORY = 342,     /* PARSEOP_DWORDMEMORY  */
    PARSEOP_DWORDPCC = 343,        /* PARSEOP_DWORDPCC  */
    PARSEOP_DWORDSPACE = 344,      /* PARSEOP_DWORDSPACE  */
    PARSEOP_EISAID = 345,          /* PARSEOP_EISAID  */
    PARSEOP_ELSE = 346,            /* PARSEOP_ELSE  */
    PARSEOP_ELSEIF = 347,          /* PARSEOP_ELSEIF  */
    PARSEOP_ENDDEPENDENTFN = 348,  /* PARSEOP_ENDDEPENDENTFN  */
    PARSEOP_ENDIAN_BIG = 349,      /* PARSEOP_ENDIAN_BIG  */
    PARSEOP_ENDIAN_LITTLE = 350,   /* PARSEOP_ENDIAN_LITTLE  */
    PARSEOP_ENDTAG = 351,          /* PARSEOP_ENDTAG  */
    PARSEOP_ERRORNODE = 352,       /* PARSEOP_ERRORNODE  */
    PARSEOP_EVENT = 353,           /* PARSEOP_EVENT  */
    PARSEOP_EXTENDEDIO = 354,      /* PARSEOP_EXTENDEDIO  */
    PARSEOP_EXTENDEDMEMORY = 355,  /* PARSEOP_EXTENDEDMEMORY  */
    PARSEOP_EXTENDEDSPACE = 356,   /* PARSEOP_EXTENDEDSPACE  */
    PARSEOP_EXTERNAL = 357,        /* PARSEOP_EXTERNAL  */
    PARSEOP_FATAL = 358,           /* PARSEOP_FATAL  */
    PARSEOP_FIELD = 359,           /* PARSEOP_FIELD  */
    PARSEOP_FINDSETLEFTBIT = 360,  /* PARSEOP_FINDSETLEFTBIT  */
    PARSEOP_FINDSETRIGHTBIT = 361, /* PARSEOP_FINDSETRIGHTBIT  */
    PARSEOP_FIXEDDMA = 362,        /* PARSEOP_FIXEDDMA  */
    PARSEOP_FIXEDIO = 363,         /* PARSEOP_FIXEDIO  */
    PARSEOP_FLOWCONTROL_HW = 364,  /* PARSEOP_FLOWCONTROL_HW  */
    PARSEOP_FLOWCONTROL_NONE = 365, /* PARSEOP_FLOWCONTROL_NONE  */
    PARSEOP_FLOWCONTROL_SW = 366,  /* PARSEOP_FLOWCONTROL_SW  */
    PARSEOP_FROMBCD = 367,         /* PARSEOP_FROMBCD  */
    PARSEOP_FUNCTION = 368,        /* PARSEOP_FUNCTION  */
    PARSEOP_GPIO_INT = 369,        /* PARSEOP_GPIO_INT  */
    PARSEOP_GPIO_IO = 370,         /* PARSEOP_GPIO_IO  */
    PARSEOP_CSI2_SERIALBUS = 371,  /* PARSEOP_CSI2_SERIALBUS  */
    PARSEOP_I2C_SERIALBUS = 372,   /* PARSEOP_I2C_SERIALBUS  */
    PARSEOP_I2C_SERIALBUS_V2 = 373, /* PARSEOP_I2C_SERIALBUS_V2  */
    PARSEOP_IF = 374,              /* PARSEOP_IF  */
    PARSEOP_INCLUDE = 375,         /* PARSEOP_INCLUDE  */
    PARSEOP_INCLUDE_END = 376,     /* PARSEOP_INCLUDE_END  */
    PARSEOP_INCREMENT = 377,       /* PARSEOP_INCREMENT  */
    PARSEOP_INDEX = 378,           /* PARSEOP_INDEX  */
    PARSEOP_INDEXFIELD = 379,      /* PARSEOP_INDEXFIELD  */
    PARSEOP_INTEGER = 380,         /* PARSEOP_INTEGER  */
    PARSEOP_INTERRUPT = 381,       /* PARSEOP_INTERRUPT  */
    PARSEOP_INTLEVEL_ACTIVEBOTH = 382, /* PARSEOP_INTLEVEL_ACTIVEBOTH  */
    PARSEOP_INTLEVEL_ACTIVEHIGH = 383, /* PARSEOP_INTLEVEL_ACTIVEHIGH  */
    PARSEOP_INTLEVEL_ACTIVELOW = 384, /* PARSEOP_INTLEVEL_ACTIVELOW  */
    PARSEOP_INTTYPE_EDGE = 385,    /* PARSEOP_INTTYPE_EDGE  */
    PARSEOP_INTTYPE_LEVEL = 386,   /* PARSEOP_INTTYPE_LEVEL  */
    PARSEOP_IO = 387,              /* PARSEOP_IO  */
    PARSEOP_IODECODETYPE_10 = 388, /* PARSEOP_IODECODETYPE_10  */
    PARSEOP_IODECODETYPE_16 = 389, /* PARSEOP_IODECODETYPE_16  */
    PARSEOP_IORESTRICT_IN = 390,   /* PARSEOP_IORESTRICT_IN  */
    PARSEOP_IORESTRICT_NONE = 391, /* PARSEOP_IORESTRICT_NONE  */
    PARSEOP_IORESTRICT_OUT = 392,  /* PARSEOP_IORESTRICT_OUT  */
    PARSEOP_IORESTRICT_PRESERVE = 393, /* PARSEOP_IORESTRICT_PRESERVE  */
    PARSEOP_IRQ = 394,             /* PARSEOP_IRQ  */
    PARSEOP_IRQNOFLAGS = 395,      /* PARSEOP_IRQNOFLAGS  */
    PARSEOP_LAND = 396,            /* PARSEOP_LAND  */
    PARSEOP_LEQUAL = 397,          /* PARSEOP_LEQUAL  */
    PARSEOP_LGREATER = 398,        /* PARSEOP_LGREATER  */
    PARSEOP_LGREATEREQUAL = 399,   /* PARSEOP_LGREATEREQUAL  */
    PARSEOP_LLESS = 400,           /* PARSEOP_LLESS  */
    PARSEOP_LLESSEQUAL = 401,      /* PARSEOP_LLESSEQUAL  */
    PARSEOP_LNOT = 402,            /* PARSEOP_LNOT  */
    PARSEOP_LNOTEQUAL = 403,       /* PARSEOP_LNOTEQUAL  */
    PARSEOP_LOAD = 404,            /* PARSEOP_LOAD  */
    PARSEOP_LOADTABLE = 405,       /* PARSEOP_LOADTABLE  */
    PARSEOP_LOCAL0 = 406,          /* PARSEOP_LOCAL0  */
    PARSEOP_LOCAL1 = 407,          /* PARSEOP_LOCAL1  */
    PARSEOP_LOCAL2 = 408,          /* PARSEOP_LOCAL2  */
    PARSEOP_LOCAL3 = 409,          /* PARSEOP_LOCAL3  */
    PARSEOP_LOCAL4 = 410,          /* PARSEOP_LOCAL4  */
    PARSEOP_LOCAL5 = 411,          /* PARSEOP_LOCAL5  */
    PARSEOP_LOCAL6 = 412,          /* PARSEOP_LOCAL6  */
    PARSEOP_LOCAL7 = 413,          /* PARSEOP_LOCAL7  */
    PARSEOP_LOCKRULE_LOCK = 414,   /* PARSEOP_LOCKRULE_LOCK  */
    PARSEOP_LOCKRULE_NOLOCK = 415, /* PARSEOP_LOCKRULE_NOLOCK  */
    PARSEOP_LOR = 416,             /* PARSEOP_LOR  */
    PARSEOP_MATCH = 417,           /* PARSEOP_MATCH  */
    PARSEOP_MATCHTYPE_MEQ = 418,   /* PARSEOP_MATCHTYPE_MEQ  */
    PARSEOP_MATCHTYPE_MGE = 419,   /* PARSEOP_MATCHTYPE_MGE  */
    PARSEOP_MATCHTYPE_MGT = 420,   /* PARSEOP_MATCHTYPE_MGT  */
    PARSEOP_MATCHTYPE_MLE = 421,   /* PARSEOP_MATCHTYPE_MLE  */
    PARSEOP_MATCHTYPE_MLT = 422,   /* PARSEOP_MATCHTYPE_MLT  */
    PARSEOP_MATCHTYPE_MTR = 423,   /* PARSEOP_MATCHTYPE_MTR  */
    PARSEOP_MAXTYPE_FIXED = 424,   /* PARSEOP_MAXTYPE_FIXED  */
    PARSEOP_MAXTYPE_NOTFIXED = 425, /* PARSEOP_MAXTYPE_NOTFIXED  */
    PARSEOP_MEMORY24 = 426,        /* PARSEOP_MEMORY24  */
    PARSEOP_MEMORY32 = 427,        /* PARSEOP_MEMORY32  */
    PARSEOP_MEMORY32FIXED = 428,   /* PARSEOP_MEMORY32FIXED  */
    PARSEOP_MEMTYPE_CACHEABLE = 429, /* PARSEOP_MEMTYPE_CACHEABLE  */
    PARSEOP_MEMTYPE_NONCACHEABLE = 430, /* PARSEOP_MEMTYPE_NONCACHEABLE  */
    PARSEOP_MEMTYPE_PREFETCHABLE = 431, /* PARSEOP_MEMTYPE_PREFETCHABLE  */
    PARSEOP_MEMTYPE_WRITECOMBINING = 432, /* PARSEOP_MEMTYPE_WRITECOMBINING  */
    PARSEOP_METHOD = 433,          /* PARSEOP_METHOD  */
    PARSEOP_METHODCALL = 434,      /* PARSEOP_METHODCALL  */
    PARSEOP_MID = 435,             /* PARSEOP_MID  */
    PARSEOP_MINTYPE_FIXED = 436,   /* PARSEOP_MINTYPE_FIXED  */
    PARSEOP_MINTYPE_NOTFIXED = 437, /* PARSEOP_MINTYPE_NOTFIXED  */
    PARSEOP_MOD = 438,             /* PARSEOP_MOD  */
    PARSEOP_MULTIPLY = 439,        /* PARSEOP_MULTIPLY  */
    PARSEOP_MUTEX = 440,           /* PARSEOP_MUTEX  */
    PARSEOP_NAME = 441,            /* PARSEOP_NAME  */
    PARSEOP_NAMESEG = 442,         /* PARSEOP_NAMESEG  */
    PARSEOP_NAMESTRING = 443,      /* PARSEOP_NAMESTRING  */
    PARSEOP_NAND = 444,            /* PARSEOP_NAND  */
    PARSEOP_NOOP = 445,            /* PARSEOP_NOOP  */
    PARSEOP_NOR = 446,             /* PARSEOP_NOR  */
    PARSEOP_NOT = 447,             /* PARSEOP_NOT  */
    PARSEOP_NOTIFY = 448,          /* PARSEOP_NOTIFY  */
    PARSEOP_OBJECTTYPE = 449,      /* PARSEOP_OBJECTTYPE  */
    PARSEOP_OBJECTTYPE_BFF = 450,  /* PARSEOP_OBJECTTYPE_BFF  */
    PARSEOP_OBJECTTYPE_BUF = 451,  /* PARSEOP_OBJECTTYPE_BUF  */
    PARSEOP_OBJECTTYPE_DDB = 452,  /* PARSEOP_OBJECTTYPE_DDB  */
    PARSEOP_OBJECTTYPE_DEV = 453,  /* PARSEOP_OBJECTTYPE_DEV  */
    PARSEOP_OBJECTTYPE_EVT = 454,  /* PARSEOP_OBJECTTYPE_EVT  */
    PARSEOP_OBJECTTYPE_FLD = 455,  /* PARSEOP_OBJECTTYPE_FLD  */
    PARSEOP_OBJECTTYPE_INT = 456,  /* PARSEOP_OBJECTTYPE_INT  */
    PARSEOP_OBJECTTYPE_MTH = 457,  /* PARSEOP_OBJECTTYPE_MTH  */
    PARSEOP_OBJECTTYPE_MTX = 458,  /* PARSEOP_OBJECTTYPE_MTX  */
    PARSEOP_OBJECTTYPE_OPR = 459,  /* PARSEOP_OBJECTTYPE_OPR  */
    PARSEOP_OBJECTTYPE_PKG = 460,  /* PARSEOP_OBJECTTYPE_PKG  */
    PARSEOP_OBJECTTYPE_POW = 461,  /* PARSEOP_OBJECTTYPE_POW  */
    PARSEOP_OBJECTTYPE_PRO = 462,  /* PARSEOP_OBJECTTYPE_PRO  */
    PARSEOP_OBJECTTYPE_STR = 463,  /* PARSEOP_OBJECTTYPE_STR  */
    PARSEOP_OBJECTTYPE_THZ = 464,  /* PARSEOP_OBJECTTYPE_THZ  */
    PARSEOP_OBJECTTYPE_UNK = 465,  /* PARSEOP_OBJECTTYPE_UNK  */
    PARSEOP_OFFSET = 466,          /* PARSEOP_OFFSET  */
    PARSEOP_ONE = 467,             /* PARSEOP_ONE  */
    PARSEOP_ONES = 468,            /* PARSEOP_ONES  */
    PARSEOP_OPERATIONREGION = 469, /* PARSEOP_OPERATIONREGION  */
    PARSEOP_OR = 470,              /* PARSEOP_OR  */
    PARSEOP_PACKAGE = 471,         /* PARSEOP_PACKAGE  */
    PARSEOP_PACKAGE_LENGTH = 472,  /* PARSEOP_PACKAGE_LENGTH  */
    PARSEOP_PARITYTYPE_EVEN = 473, /* PARSEOP_PARITYTYPE_EVEN  */
    PARSEOP_PARITYTYPE_MARK = 474, /* PARSEOP_PARITYTYPE_MARK  */
    PARSEOP_PARITYTYPE_NONE = 475, /* PARSEOP_PARITYTYPE_NONE  */
    PARSEOP_PARITYTYPE_ODD = 476,  /* PARSEOP_PARITYTYPE_ODD  */
    PARSEOP_PARITYTYPE_SPACE = 477, /* PARSEOP_PARITYTYPE_SPACE  */
    PARSEOP_PINCONFIG = 478,       /* PARSEOP_PINCONFIG  */
    PARSEOP_PINFUNCTION = 479,     /* PARSEOP_PINFUNCTION  */
    PARSEOP_PINGROUP = 480,        /* PARSEOP_PINGROUP  */
    PARSEOP_PINGROUPCONFIG = 481,  /* PARSEOP_PINGROUPCONFIG  */
    PARSEOP_PINGROUPFUNCTION = 482, /* PARSEOP_PINGROUPFUNCTION  */
    PARSEOP_PIN_NOPULL = 483,      /* PARSEOP_PIN_NOPULL  */
    PARSEOP_PIN_PULLDEFAULT = 484, /* PARSEOP_PIN_PULLDEFAULT  */
    PARSEOP_PIN_PULLDOWN = 485,    /* PARSEOP_PIN_PULLDOWN  */
    PARSEOP_PIN_PULLUP = 486,      /* PARSEOP_PIN_PULLUP  */
    PARSEOP_CLOCKINPUT = 487,      /* PARSEOP_CLOCKINPUT  */
    PARSEOP_CLOCK_HZ = 488,        /* PARSEOP_CLOCK_HZ  */
    PARSEOP_CLOCK_KHZ = 489,       /* PARSEOP_CLOCK_KHZ  */
    PARSEOP_CLOCK_MHZ = 490,       /* PARSEOP_CLOCK_MHZ  */
    PARSEOP_CLOCK_FIXED = 491,     /* PARSEOP_CLOCK_FIXED  */
    PARSEOP_CLOCK_VARIABLE = 492,  /* PARSEOP_CLOCK_VARIABLE  */
    PARSEOP_POWERRESOURCE = 493,   /* PARSEOP_POWERRESOURCE  */
    PARSEOP_PROCESSOR = 494,       /* PARSEOP_PROCESSOR  */
    PARSEOP_QWORDCONST = 495,      /* PARSEOP_QWORDCONST  */
    PARSEOP_QWORDIO = 496,         /* PARSEOP_QWORDIO  */
    PARSEOP_QWORDMEMORY = 497,     /* PARSEOP_QWORDMEMORY  */
    PARSEOP_QWORDPCC = 498,        /* PARSEOP_QWORDPCC  */
    PARSEOP_QWORDSPACE = 499,      /* PARSEOP_QWORDSPACE  */
    PARSEOP_RANGETYPE_ENTIRE = 500, /* PARSEOP_RANGETYPE_ENTIRE  */
    PARSEOP_RANGETYPE_ISAONLY = 501, /* PARSEOP_RANGETYPE_ISAONLY  */
    PARSEOP_RANGETYPE_NONISAONLY = 502, /* PARSEOP_RANGETYPE_NONISAONLY  */
    PARSEOP_RAW_DATA = 503,        /* PARSEOP_RAW_DATA  */
    PARSEOP_READWRITETYPE_BOTH = 504, /* PARSEOP_READWRITETYPE_BOTH  */
    PARSEOP_READWRITETYPE_READONLY = 505, /* PARSEOP_READWRITETYPE_READONLY  */
    PARSEOP_REFOF = 506,           /* PARSEOP_REFOF  */
    PARSEOP_REGIONSPACE_CMOS = 507, /* PARSEOP_REGIONSPACE_CMOS  */
    PARSEOP_REGIONSPACE_EC = 508,  /* PARSEOP_REGIONSPACE_EC  */
    PARSEOP_REGIONSPACE_FFIXEDHW = 509, /* PARSEOP_REGIONSPACE_FFIXEDHW  */
    PARSEOP_REGIONSPACE_GPIO = 510, /* PARSEOP_REGIONSPACE_GPIO  */
    PARSEOP_REGIONSPACE_GSBUS = 511, /* PARSEOP_REGIONSPACE_GSBUS  */
    PARSEOP_REGIONSPACE_IO = 512,  /* PARSEOP_REGIONSPACE_IO  */
    PARSEOP_REGIONSPACE_IPMI = 513, /* PARSEOP_REGIONSPACE_IPMI  */
    PARSEOP_REGIONSPACE_MEM = 514, /* PARSEOP_REGIONSPACE_MEM  */
    PARSEOP_REGIONSPACE_PCC = 515, /* PARSEOP_REGIONSPACE_PCC  */
    PARSEOP_REGIONSPACE_PCI = 516, /* PARSEOP_REGIONSPACE_PCI  */
    PARSEOP_REGIONSPACE_PCIBAR = 517, /* PARSEOP_REGIONSPACE_PCIBAR  */
    PARSEOP_REGIONSPACE_PRM = 518, /* PARSEOP_REGIONSPACE_PRM  */
    PARSEOP_REGIONSPACE_SMBUS = 519, /* PARSEOP_REGIONSPACE_SMBUS  */
    PARSEOP_REGISTER = 520,        /* PARSEOP_REGISTER  */
    PARSEOP_RELEASE = 521,         /* PARSEOP_RELEASE  */
    PARSEOP_RESERVED_BYTES = 522,  /* PARSEOP_RESERVED_BYTES  */
    PARSEOP_RESET = 523,           /* PARSEOP_RESET  */
    PARSEOP_RESOURCETEMPLATE = 524, /* PARSEOP_RESOURCETEMPLATE  */
    PARSEOP_RESOURCETYPE_CONSUMER = 525, /* PARSEOP_RESOURCETYPE_CONSUMER  */
    PARSEOP_RESOURCETYPE_PRODUCER = 526, /* PARSEOP_RESOURCETYPE_PRODUCER  */
    PARSEOP_RETURN = 527,          /* PARSEOP_RETURN  */
    PARSEOP_REVISION = 528,        /* PARSEOP_REVISION  */
    PARSEOP_SCOPE = 529,           /* PARSEOP_SCOPE  */
    PARSEOP_SERIALIZERULE_NOTSERIAL = 530, /* PARSEOP_SERIALIZERULE_NOTSERIAL  */
    PARSEOP_SERIALIZERULE_SERIAL = 531, /* PARSEOP_SERIALIZERULE_SERIAL  */
    PARSEOP_SHARETYPE_EXCLUSIVE = 532, /* PARSEOP_SHARETYPE_EXCLUSIVE  */
    PARSEOP_SHARETYPE_EXCLUSIVEWAKE = 533, /* PARSEOP_SHARETYPE_EXCLUSIVEWAKE  */
    PARSEOP_SHARETYPE_SHARED = 534, /* PARSEOP_SHARETYPE_SHARED  */
    PARSEOP_SHARETYPE_SHAREDWAKE = 535, /* PARSEOP_SHARETYPE_SHAREDWAKE  */
    PARSEOP_SHIFTLEFT = 536,       /* PARSEOP_SHIFTLEFT  */
    PARSEOP_SHIFTRIGHT = 537,      /* PARSEOP_SHIFTRIGHT  */
    PARSEOP_SIGNAL = 538,          /* PARSEOP_SIGNAL  */
    PARSEOP_SIZEOF = 539,          /* PARSEOP_SIZEOF  */
    PARSEOP_SLAVEMODE_CONTROLLERINIT = 540, /* PARSEOP_SLAVEMODE_CONTROLLERINIT  */
    PARSEOP_SLAVEMODE_DEVICEINIT = 541, /* PARSEOP_SLAVEMODE_DEVICEINIT  */
    PARSEOP_SLEEP = 542,           /* PARSEOP_SLEEP  */
    PARSEOP_SPI_SERIALBUS = 543,   /* PARSEOP_SPI_SERIALBUS  */
    PARSEOP_SPI_SERIALBUS_V2 = 544, /* PARSEOP_SPI_SERIALBUS_V2  */
    PARSEOP_STALL = 545,           /* PARSEOP_STALL  */
    PARSEOP_STARTDEPENDENTFN = 546, /* PARSEOP_STARTDEPENDENTFN  */
    PARSEOP_STARTDEPENDENTFN_NOPRI = 547, /* PARSEOP_STARTDEPENDENTFN_NOPRI  */
    PARSEOP_STOPBITS_ONE = 548,    /* PARSEOP_STOPBITS_ONE  */
    PARSEOP_STOPBITS_ONEPLUSHALF = 549, /* PARSEOP_STOPBITS_ONEPLUSHALF  */
    PARSEOP_STOPBITS_TWO = 550,    /* PARSEOP_STOPBITS_TWO  */
    PARSEOP_STOPBITS_ZERO = 551,   /* PARSEOP_STOPBITS_ZERO  */
    PARSEOP_STORE = 552,           /* PARSEOP_STORE  */
    PARSEOP_STRING_LITERAL = 553,  /* PARSEOP_STRING_LITERAL  */
    PARSEOP_SUBTRACT = 554,        /* PARSEOP_SUBTRACT  */
    PARSEOP_SWITCH = 555,          /* PARSEOP_SWITCH  */
    PARSEOP_THERMALZONE = 556,     /* PARSEOP_THERMALZONE  */
    PARSEOP_TIMER = 557,           /* PARSEOP_TIMER  */
    PARSEOP_TOBCD = 558,           /* PARSEOP_TOBCD  */
    PARSEOP_TOBUFFER = 559,        /* PARSEOP_TOBUFFER  */
    PARSEOP_TODECIMALSTRING = 560, /* PARSEOP_TODECIMALSTRING  */
    PARSEOP_TOHEXSTRING = 561,     /* PARSEOP_TOHEXSTRING  */
    PARSEOP_TOINTEGER = 562,       /* PARSEOP_TOINTEGER  */
    PARSEOP_TOSTRING = 563,        /* PARSEOP_TOSTRING  */
    PARSEOP_TOUUID = 564,          /* PARSEOP_TOUUID  */
    PARSEOP_TRANSLATIONTYPE_DENSE = 565, /* PARSEOP_TRANSLATIONTYPE_DENSE  */
    PARSEOP_TRANSLATIONTYPE_SPARSE = 566, /* PARSEOP_TRANSLATIONTYPE_SPARSE  */
    PARSEOP_TYPE_STATIC = 567,     /* PARSEOP_TYPE_STATIC  */
    PARSEOP_TYPE_TRANSLATION = 568, /* PARSEOP_TYPE_TRANSLATION  */
    PARSEOP_UART_SERIALBUS = 569,  /* PARSEOP_UART_SERIALBUS  */
    PARSEOP_UART_SERIALBUS_V2 = 570, /* PARSEOP_UART_SERIALBUS_V2  */
    PARSEOP_UNICODE = 571,         /* PARSEOP_UNICODE  */
    PARSEOP_UNLOAD = 572,          /* PARSEOP_UNLOAD  */
    PARSEOP_UPDATERULE_ONES = 573, /* PARSEOP_UPDATERULE_ONES  */
    PARSEOP_UPDATERULE_PRESERVE = 574, /* PARSEOP_UPDATERULE_PRESERVE  */
    PARSEOP_UPDATERULE_ZEROS = 575, /* PARSEOP_UPDATERULE_ZEROS  */
    PARSEOP_VAR_PACKAGE = 576,     /* PARSEOP_VAR_PACKAGE  */
    PARSEOP_VENDORLONG = 577,      /* PARSEOP_VENDORLONG  */
    PARSEOP_VENDORSHORT = 578,     /* PARSEOP_VENDORSHORT  */
    PARSEOP_WAIT = 579,            /* PARSEOP_WAIT  */
    PARSEOP_WHILE = 580,           /* PARSEOP_WHILE  */
    PARSEOP_WIREMODE_FOUR = 581,   /* PARSEOP_WIREMODE_FOUR  */
    PARSEOP_WIREMODE_THREE = 582,  /* PARSEOP_WIREMODE_THREE  */
    PARSEOP_WORDBUSNUMBER = 583,   /* PARSEOP_WORDBUSNUMBER  */
    PARSEOP_WORDCONST = 584,       /* PARSEOP_WORDCONST  */
    PARSEOP_WORDIO = 585,          /* PARSEOP_WORDIO  */
    PARSEOP_WORDPCC = 586,         /* PARSEOP_WORDPCC  */
    PARSEOP_WORDSPACE = 587,       /* PARSEOP_WORDSPACE  */
    PARSEOP_XFERSIZE_8 = 588,      /* PARSEOP_XFERSIZE_8  */
    PARSEOP_XFERSIZE_16 = 589,     /* PARSEOP_XFERSIZE_16  */
    PARSEOP_XFERSIZE_32 = 590,     /* PARSEOP_XFERSIZE_32  */
    PARSEOP_XFERSIZE_64 = 591,     /* PARSEOP_XFERSIZE_64  */
    PARSEOP_XFERSIZE_128 = 592,    /* PARSEOP_XFERSIZE_128  */
    PARSEOP_XFERSIZE_256 = 593,    /* PARSEOP_XFERSIZE_256  */
    PARSEOP_XFERTYPE_8 = 594,      /* PARSEOP_XFERTYPE_8  */
    PARSEOP_XFERTYPE_8_16 = 595,   /* PARSEOP_XFERTYPE_8_16  */
    PARSEOP_XFERTYPE_16 = 596,     /* PARSEOP_XFERTYPE_16  */
    PARSEOP_XOR = 597,             /* PARSEOP_XOR  */
    PARSEOP_ZERO = 598,            /* PARSEOP_ZERO  */
    PARSEOP_TOPLD = 599,           /* PARSEOP_TOPLD  */
    PARSEOP_PLD_REVISION = 600,    /* PARSEOP_PLD_REVISION  */
    PARSEOP_PLD_IGNORECOLOR = 601, /* PARSEOP_PLD_IGNORECOLOR  */
    PARSEOP_PLD_RED = 602,         /* PARSEOP_PLD_RED  */
    PARSEOP_PLD_GREEN = 603,       /* PARSEOP_PLD_GREEN  */
    PARSEOP_PLD_BLUE = 604,        /* PARSEOP_PLD_BLUE  */
    PARSEOP_PLD_WIDTH = 605,       /* PARSEOP_PLD_WIDTH  */
    PARSEOP_PLD_HEIGHT = 606,      /* PARSEOP_PLD_HEIGHT  */
    PARSEOP_PLD_USERVISIBLE = 607, /* PARSEOP_PLD_USERVISIBLE  */
    PARSEOP_PLD_DOCK = 608,        /* PARSEOP_PLD_DOCK  */
    PARSEOP_PLD_LID = 609,         /* PARSEOP_PLD_LID  */
    PARSEOP_PLD_PANEL = 610,       /* PARSEOP_PLD_PANEL  */
    PARSEOP_PLD_VERTICALPOSITION = 611, /* PARSEOP_PLD_VERTICALPOSITION  */
    PARSEOP_PLD_HORIZONTALPOSITION = 612, /* PARSEOP_PLD_HORIZONTALPOSITION  */
    PARSEOP_PLD_SHAPE = 613,       /* PARSEOP_PLD_SHAPE  */
    PARSEOP_PLD_GROUPORIENTATION = 614, /* PARSEOP_PLD_GROUPORIENTATION  */
    PARSEOP_PLD_GROUPTOKEN = 615,  /* PARSEOP_PLD_GROUPTOKEN  */
    PARSEOP_PLD_GROUPPOSITION = 616, /* PARSEOP_PLD_GROUPPOSITION  */
    PARSEOP_PLD_BAY = 617,         /* PARSEOP_PLD_BAY  */
    PARSEOP_PLD_EJECTABLE = 618,   /* PARSEOP_PLD_EJECTABLE  */
    PARSEOP_PLD_EJECTREQUIRED = 619, /* PARSEOP_PLD_EJECTREQUIRED  */
    PARSEOP_PLD_CABINETNUMBER = 620, /* PARSEOP_PLD_CABINETNUMBER  */
    PARSEOP_PLD_CARDCAGENUMBER = 621, /* PARSEOP_PLD_CARDCAGENUMBER  */
    PARSEOP_PLD_REFERENCE = 622,   /* PARSEOP_PLD_REFERENCE  */
    PARSEOP_PLD_ROTATION = 623,    /* PARSEOP_PLD_ROTATION  */
    PARSEOP_PLD_ORDER = 624,       /* PARSEOP_PLD_ORDER  */
    PARSEOP_PLD_RESERVED = 625,    /* PARSEOP_PLD_RESERVED  */
    PARSEOP_PLD_VERTICALOFFSET = 626, /* PARSEOP_PLD_VERTICALOFFSET  */
    PARSEOP_PLD_HORIZONTALOFFSET = 627, /* PARSEOP_PLD_HORIZONTALOFFSET  */
    PARSEOP_EXP_EQUALS = 628,      /* PARSEOP_EXP_EQUALS  */
    PARSEOP_EXP_ADD_EQ = 629,      /* PARSEOP_EXP_ADD_EQ  */
    PARSEOP_EXP_SUB_EQ = 630,      /* PARSEOP_EXP_SUB_EQ  */
    PARSEOP_EXP_MUL_EQ = 631,      /* PARSEOP_EXP_MUL_EQ  */
    PARSEOP_EXP_DIV_EQ = 632,      /* PARSEOP_EXP_DIV_EQ  */
    PARSEOP_EXP_MOD_EQ = 633,      /* PARSEOP_EXP_MOD_EQ  */
    PARSEOP_EXP_SHL_EQ = 634,      /* PARSEOP_EXP_SHL_EQ  */
    PARSEOP_EXP_SHR_EQ = 635,      /* PARSEOP_EXP_SHR_EQ  */
    PARSEOP_EXP_AND_EQ = 636,      /* PARSEOP_EXP_AND_EQ  */
    PARSEOP_EXP_XOR_EQ = 637,      /* PARSEOP_EXP_XOR_EQ  */
    PARSEOP_EXP_OR_EQ = 638,       /* PARSEOP_EXP_OR_EQ  */
    PARSEOP_EXP_LOGICAL_OR = 639,  /* PARSEOP_EXP_LOGICAL_OR  */
    PARSEOP_EXP_LOGICAL_AND = 640, /* PARSEOP_EXP_LOGICAL_AND  */
    PARSEOP_EXP_OR = 641,          /* PARSEOP_EXP_OR  */
    PARSEOP_EXP_XOR = 642,         /* PARSEOP_EXP_XOR  */
    PARSEOP_EXP_AND = 643,         /* PARSEOP_EXP_AND  */
    PARSEOP_EXP_EQUAL = 644,       /* PARSEOP_EXP_EQUAL  */
    PARSEOP_EXP_NOT_EQUAL = 645,   /* PARSEOP_EXP_NOT_EQUAL  */
    PARSEOP_EXP_GREATER = 646,     /* PARSEOP_EXP_GREATER  */
    PARSEOP_EXP_LESS = 647,        /* PARSEOP_EXP_LESS  */
    PARSEOP_EXP_GREATER_EQUAL = 648, /* PARSEOP_EXP_GREATER_EQUAL  */
    PARSEOP_EXP_LESS_EQUAL = 649,  /* PARSEOP_EXP_LESS_EQUAL  */
    PARSEOP_EXP_SHIFT_RIGHT = 650, /* PARSEOP_EXP_SHIFT_RIGHT  */
    PARSEOP_EXP_SHIFT_LEFT = 651,  /* PARSEOP_EXP_SHIFT_LEFT  */
    PARSEOP_EXP_ADD = 652,         /* PARSEOP_EXP_ADD  */
    PARSEOP_EXP_SUBTRACT = 653,    /* PARSEOP_EXP_SUBTRACT  */
    PARSEOP_EXP_MULTIPLY = 654,    /* PARSEOP_EXP_MULTIPLY  */
    PARSEOP_EXP_DIVIDE = 655,      /* PARSEOP_EXP_DIVIDE  */
    PARSEOP_EXP_MODULO = 656,      /* PARSEOP_EXP_MODULO  */
    PARSEOP_EXP_NOT = 657,         /* PARSEOP_EXP_NOT  */
    PARSEOP_EXP_LOGICAL_NOT = 658, /* PARSEOP_EXP_LOGICAL_NOT  */
    PARSEOP_EXP_INCREMENT = 659,   /* PARSEOP_EXP_INCREMENT  */
    PARSEOP_EXP_DECREMENT = 660,   /* PARSEOP_EXP_DECREMENT  */
    PARSEOP_OPEN_PAREN = 661,      /* PARSEOP_OPEN_PAREN  */
    PARSEOP_CLOSE_PAREN = 662,     /* PARSEOP_CLOSE_PAREN  */
    PARSEOP_EXP_INDEX_LEFT = 663,  /* PARSEOP_EXP_INDEX_LEFT  */
    PARSEOP_EXP_INDEX_RIGHT = 664, /* PARSEOP_EXP_INDEX_RIGHT  */
    PARSEOP_PRINTF = 665,          /* PARSEOP_PRINTF  */
    PARSEOP_FPRINTF = 666,         /* PARSEOP_FPRINTF  */
    PARSEOP_FOR = 667,             /* PARSEOP_FOR  */
    PARSEOP_STRUCTURE = 668,       /* PARSEOP_STRUCTURE  */
    PARSEOP_STRUCTURE_NAMESTRING = 669, /* PARSEOP_STRUCTURE_NAMESTRING  */
    PARSEOP_STRUCTURE_TAG = 670,   /* PARSEOP_STRUCTURE_TAG  */
    PARSEOP_STRUCTURE_ELEMENT = 671, /* PARSEOP_STRUCTURE_ELEMENT  */
    PARSEOP_STRUCTURE_INSTANCE = 672, /* PARSEOP_STRUCTURE_INSTANCE  */
    PARSEOP_STRUCTURE_REFERENCE = 673, /* PARSEOP_STRUCTURE_REFERENCE  */
    PARSEOP_STRUCTURE_POINTER = 674, /* PARSEOP_STRUCTURE_POINTER  */
    PARSEOP_ASL_CODE = 675,        /* PARSEOP_ASL_CODE  */
    PARSEOP_INTEGER_TYPE = 676,    /* PARSEOP_INTEGER_TYPE  */
    PARSEOP_STRING_TYPE = 677,     /* PARSEOP_STRING_TYPE  */
    PARSEOP_BUFFER_TYPE = 678,     /* PARSEOP_BUFFER_TYPE  */
    PARSEOP_PACKAGE_TYPE = 679,    /* PARSEOP_PACKAGE_TYPE  */
    PARSEOP_REFERENCE_TYPE = 680,  /* PARSEOP_REFERENCE_TYPE  */
    PARSEOP___DATE__ = 681,        /* PARSEOP___DATE__  */
    PARSEOP___FILE__ = 682,        /* PARSEOP___FILE__  */
    PARSEOP___LINE__ = 683,        /* PARSEOP___LINE__  */
    PARSEOP___PATH__ = 684,        /* PARSEOP___PATH__  */
    PARSEOP___METHOD__ = 685       /* PARSEOP___METHOD__  */
  };
  typedef enum yytokentype yytoken_kind_t;
#endif

/* Value type.  */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED
union YYSTYPE
{

    UINT64              i;
    char                *s;
    ACPI_PARSE_OBJECT   *n;


};
typedef union YYSTYPE YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif


extern YYSTYPE AslCompilerlval;


int AslCompilerparse (void);


#endif /* !YY_ASLCOMPILER_GENERATE_MSVC2017_ASLCOMPILER_Y_H_INCLUDED  */
